
#include <Arduino.h> // Standard Arduino Library
#include <FastLED.h>

#ifndef MAIN_H // Makro-Wächter, um Mehrfachinklusionen zu verhindern
#define MAIN_H


#define WS28XX_LED_PIN 33 // GPIO 33
#define NUM_LEDS  13

uint8_t __BRIGHTNESS = 85;

uint32_t __btnLookUpTable[141] = {
  CRGB::HTMLColorCode::AliceBlue,
  CRGB::HTMLColorCode::Amethyst,
  CRGB::HTMLColorCode::AntiqueWhite,
  CRGB::HTMLColorCode::Aqua,
  CRGB::HTMLColorCode::Aquamarine,
  CRGB::HTMLColorCode::Azure,
  CRGB::HTMLColorCode::Beige,
  CRGB::HTMLColorCode::Bisque,
  CRGB::HTMLColorCode::Black,
  CRGB::HTMLColorCode::BlanchedAlmond,
  CRGB::HTMLColorCode::Blue,
  CRGB::HTMLColorCode::BlueViolet,
  CRGB::HTMLColorCode::Brown,
  CRGB::HTMLColorCode::BurlyWood,
  CRGB::HTMLColorCode::CadetBlue,
  CRGB::HTMLColorCode::Chartreuse,
  CRGB::HTMLColorCode::Chocolate,
  CRGB::HTMLColorCode::Coral,
  CRGB::HTMLColorCode::CornflowerBlue,
  CRGB::HTMLColorCode::Cornsilk,
  CRGB::HTMLColorCode::Crimson,
  CRGB::HTMLColorCode::Cyan,
  CRGB::HTMLColorCode::DarkBlue,
  CRGB::HTMLColorCode::DarkCyan,
  CRGB::HTMLColorCode::DarkGoldenrod,
  CRGB::HTMLColorCode::DarkGray,
  CRGB::HTMLColorCode::DarkGreen,
  CRGB::HTMLColorCode::DarkKhaki,
  CRGB::HTMLColorCode::DarkMagenta,
  CRGB::HTMLColorCode::DarkOliveGreen,
  CRGB::HTMLColorCode::DarkOrange,
  CRGB::HTMLColorCode::DarkOrchid,
  CRGB::HTMLColorCode::DarkRed,
  CRGB::HTMLColorCode::DarkSalmon,
  CRGB::HTMLColorCode::DarkSeaGreen,
  CRGB::HTMLColorCode::DarkSlateBlue,
  CRGB::HTMLColorCode::DarkSlateGray,
  CRGB::HTMLColorCode::DarkTurquoise,
  CRGB::HTMLColorCode::DarkViolet,
  CRGB::HTMLColorCode::DeepPink,
  CRGB::HTMLColorCode::FloralWhite,
  CRGB::HTMLColorCode::ForestGreen,
  CRGB::HTMLColorCode::Fuchsia,
  CRGB::HTMLColorCode::Gainsboro,
  CRGB::HTMLColorCode::GhostWhite,
  CRGB::HTMLColorCode::Gold,
  CRGB::HTMLColorCode::Goldenrod,
  CRGB::HTMLColorCode::Gray,
  CRGB::HTMLColorCode::Green,
  CRGB::HTMLColorCode::GreenYellow,
  CRGB::HTMLColorCode::Honeydew,
  CRGB::HTMLColorCode::HotPink,
  CRGB::HTMLColorCode::IndianRed,
  CRGB::HTMLColorCode::Indigo,
  CRGB::HTMLColorCode::Ivory,
  CRGB::HTMLColorCode::Khaki,
  CRGB::HTMLColorCode::Lavender,
  CRGB::HTMLColorCode::LavenderBlush,
  CRGB::HTMLColorCode::LawnGreen,
  CRGB::HTMLColorCode::LemonChiffon,
  CRGB::HTMLColorCode::LightBlue,
  CRGB::HTMLColorCode::LightCoral,
  CRGB::HTMLColorCode::LightCyan,
  CRGB::HTMLColorCode::LightGoldenrodYellow,
  CRGB::HTMLColorCode::LightGreen,
  CRGB::HTMLColorCode::LightGrey,
  CRGB::HTMLColorCode::LightPink,
  CRGB::HTMLColorCode::LightSalmon,
  CRGB::HTMLColorCode::LightSeaGreen,
  CRGB::HTMLColorCode::LightSkyBlue,
  CRGB::HTMLColorCode::LightSlateGray,
  CRGB::HTMLColorCode::LightSlateGrey,
  CRGB::HTMLColorCode::LightSteelBlue,
  CRGB::HTMLColorCode::LightYellow,
  CRGB::HTMLColorCode::Lime,
  CRGB::HTMLColorCode::LimeGreen,
  CRGB::HTMLColorCode::Linen,
  CRGB::HTMLColorCode::Magenta,
  CRGB::HTMLColorCode::Maroon,
  CRGB::HTMLColorCode::MediumAquamarine,
  CRGB::HTMLColorCode::MediumBlue,
  CRGB::HTMLColorCode::MediumOrchid,
  CRGB::HTMLColorCode::MediumPurple,
  CRGB::HTMLColorCode::MediumSeaGreen,
  CRGB::HTMLColorCode::MediumSlateBlue,
  CRGB::HTMLColorCode::MediumSpringGreen,
  CRGB::HTMLColorCode::MediumTurquoise,
  CRGB::HTMLColorCode::MediumVioletRed,
  CRGB::HTMLColorCode::MidnightBlue,
  CRGB::HTMLColorCode::MintCream,
  CRGB::HTMLColorCode::MistyRose,
  CRGB::HTMLColorCode::Moccasin,
  CRGB::HTMLColorCode::NavajoWhite,
  CRGB::HTMLColorCode::Navy,
  CRGB::HTMLColorCode::OldLace,
  CRGB::HTMLColorCode::Olive,
  CRGB::HTMLColorCode::OliveDrab,
  CRGB::HTMLColorCode::Orange,
  CRGB::HTMLColorCode::OrangeRed,
  CRGB::HTMLColorCode::Orchid,
  CRGB::HTMLColorCode::PaleGoldenrod,
  CRGB::HTMLColorCode::PaleGreen,
  CRGB::HTMLColorCode::PaleTurquoise,
  CRGB::HTMLColorCode::PaleVioletRed,
  CRGB::HTMLColorCode::PapayaWhip,
  CRGB::HTMLColorCode::PeachPuff,
  CRGB::HTMLColorCode::Peru,
  CRGB::HTMLColorCode::Pink,
  CRGB::HTMLColorCode::Plaid,
  CRGB::HTMLColorCode::Plum,
  CRGB::HTMLColorCode::PowderBlue,
  CRGB::HTMLColorCode::Purple,
  CRGB::HTMLColorCode::Red,
  CRGB::HTMLColorCode::RosyBrown,
  CRGB::HTMLColorCode::RoyalBlue,
  CRGB::HTMLColorCode::SaddleBrown,
  CRGB::HTMLColorCode::Salmon,
  CRGB::HTMLColorCode::SandyBrown,
  CRGB::HTMLColorCode::SeaGreen,
  CRGB::HTMLColorCode::Seashell,
  CRGB::HTMLColorCode::Sienna,
  CRGB::HTMLColorCode::Silver,
  CRGB::HTMLColorCode::SkyBlue,
  CRGB::HTMLColorCode::SlateBlue,
  CRGB::HTMLColorCode::SlateGray,
  CRGB::HTMLColorCode::SlateGrey,
  CRGB::HTMLColorCode::Snow,
  CRGB::HTMLColorCode::SpringGreen,
  CRGB::HTMLColorCode::SteelBlue,
  CRGB::HTMLColorCode::Tan,
  CRGB::HTMLColorCode::Teal,
  CRGB::HTMLColorCode::Thistle,
  CRGB::HTMLColorCode::Tomato,
  CRGB::HTMLColorCode::Turquoise,
  CRGB::HTMLColorCode::Violet,
  CRGB::HTMLColorCode::Wheat,
  CRGB::HTMLColorCode::White,
  CRGB::HTMLColorCode::WhiteSmoke,
  CRGB::HTMLColorCode::Yellow,
  CRGB::HTMLColorCode::YellowGreen
};

#endif // MAIN_H
